export const AGRIYIELD_ABI = [
  {
    inputs: [
      { internalType: "address", name: "_farmShares", type: "address" },
      { internalType: "address", name: "_AGT", type: "address" },
      { internalType: "address", name: "_admin", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "ReentrancyGuardReentrantCall",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "farmId", type: "uint256" }],
    name: "FarmClosed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "farmId", type: "uint256" },
      { indexed: true, internalType: "address", name: "farmer", type: "address" },
    ],
    name: "FarmCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint256", name: "farmId", type: "uint256" }],
    name: "FarmVerified",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "farmId", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "FundDisbursed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "farmId", type: "uint256" },
      { indexed: true, internalType: "address", name: "investor", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "shares", type: "uint256" },
    ],
    name: "InvestmentMade",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "farmId", type: "uint256" },
      { indexed: true, internalType: "address", name: "investor", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "InvestorClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "farmId", type: "uint256" },
      { indexed: true, internalType: "address", name: "investor", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "InvestorRefunded",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
  {
    inputs: [],
    name: "admin",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_farmId", type: "uint256" }],
    name: "closeFarm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_name", type: "string" },
      { internalType: "string", name: "_location", type: "string" },
      { internalType: "string", name: "_cropType", type: "string" },
      { internalType: "uint256", name: "_area", type: "uint256" },
      { internalType: "uint256", name: "_fundingGoal", type: "uint256" },
      { internalType: "uint256", name: "_duration", type: "uint256" },
      { internalType: "address", name: "_farmer", type: "address" },
    ],
    name: "createFarm",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_farmId", type: "uint256" }],
    name: "depositProceeds",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_farmId", type: "uint256" }],
    name: "disburseFunds",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_farmId", type: "uint256" }],
    name: "getFarm",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "farmer", type: "address" },
          { internalType: "string", name: "name", type: "string" },
          { internalType: "string", name: "location", type: "string" },
          { internalType: "string", name: "cropType", type: "string" },
          { internalType: "uint256", name: "area", type: "uint256" },
          { internalType: "uint256", name: "fundingGoal", type: "uint256" },
          { internalType: "uint256", name: "amountRaised", type: "uint256" },
          { internalType: "uint256", name: "duration", type: "uint256" },
          { internalType: "uint256", name: "createdAt", type: "uint256" },
          { internalType: "bool", name: "verified", type: "bool" },
          { internalType: "bool", name: "fundsDisbursed", type: "bool" },
          { internalType: "bool", name: "closed", type: "bool" },
          { internalType: "uint256", name: "totalProceeds", type: "uint256" },
        ],
        internalType: "struct AgriYield.Farm",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getFarmCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_farmId", type: "uint256" }],
    name: "getInvestorShares",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_farmId", type: "uint256" },
      { internalType: "address", name: "_investor", type: "address" },
    ],
    name: "getInvestorYield",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_farmId", type: "uint256" }],
    name: "invest",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_farmId", type: "uint256" },
      { internalType: "address", name: "_investor", type: "address" },
    ],
    name: "refundInvestor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_farmId", type: "uint256" }],
    name: "verifyFarm",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_farmId", type: "uint256" },
      { internalType: "address", name: "_investor", type: "address" },
    ],
    name: "withdrawYield",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
]